AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
