name: Build and Release a new version of this gem

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: ruby
          package-name: openpix-ruby_sdk
          version-file: "lib/openpix/ruby_sdk/version.rb"
